### ISSUE TITLE
Relative elapsed time into each hit

### ISSUE THREAD

**Issue by jacopo-chevallard** [szaghi/FITTER#2]
When running the same lines of code multiple times having each hit printed separately makes the output difficult to interpret. For now I just commented out [these lines](https://github.com/szaghi/FITTER/blob/864d4c87b8922f080cfb4034803fc5ee8d8aba8a/src/lib/fitter.f90#L114-L118), but it would probably be better to have an option to print each hit or not.

**Comment by szaghi** [comment]
@jacopo-chevallard 

Another good suggestion, thanks a lot. As for the other suggestion, please wait until 6th July.

Cheers.

**Comment by jacopo-chevallard** [comment]
yep, no hurry from my side!

**Comment by jacopo-chevallard** [comment]
Another thought: it could be useful to print the snippets sorted by decreasing relative elapsed time, similarly to what profilers do, so that at the top there is the snippet contributing to most of the time, then the second, ...

**Comment by szaghi** [comment]
@jacopo-chevallard I have just found the time for a quick review at the library: do you think it is still *acceptable* if I split the library into 2 modules? I know this complicates the building of the library (having only 1 file is very handy), but I guess that adding *concurrency* will add some complexity to the source...

**Comment by jacopo-chevallard** [comment]
I don't think it complicates the building at all, I actually prefer to have a single module (and class) into each file (and use CMake for building my projects)

**Comment by szaghi** [comment]
Done, see comments in issue#1
